url<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url,destfile="./a.zip")
library(data.table)
nim<-read.table(unzip("./a.zip","household_power_consumption.txt"),sep=";",header=TRUE)
nim$Date<-as.Date(nim$Date,"%d/%m/%Y")
nim[[2]]<-as.character(nim[[2]])
nim[[2]]<-as.ITime(nim[[2]],format="%H:%M:%S")
x<-as.Date(c("2007-02-01","2007-02-02"))
nim<-nim[(nim$Date==x[1])|(nim$Date==x[2]),]
x1<-as.POSIXct(paste(nim[[1]],nim[[2]]))

#plotting starts from here

png(filename="plot4.png",height=480,width=480)
par(mfrow=c(2,2),mar=c(4,4,0,0.5))
plot(x1,as.numeric(as.character(nim[[3]])),type="n",xlab="",ylab="Global Active Power (Kilowatts)",cex.lab=0.75,cex.axis=0.5)
lines(x1,as.numeric(as.character(nim[[3]])))
with(nim,{for(i in 1:length(nim[[5]]))
        if(nim[[5]][i]=="?")
                nim[[5]][i]<-NA })
plot(x1,as.numeric(as.character(nim[[5]])),type="n",xlab="datetime",ylab="Voltage",cex.lab=0.75,cex.axis=0.5)
lines(x1,as.numeric(as.character(nim[[5]])))
with(nim,{for(i in 1:length(nim[[7]]))
        if(nim[[7]][i]=="?")
                nim[[7]][i]<-NA })
with(nim,{for(i in 1:length(nim[[8]]))
        if(nim[[8]][i]=="?")
                nim[[8]][i]<-NA })
plot(x1,as.numeric(as.character(nim[[7]])),type="n",xlab="",ylab="Energy sub metering",cex.lab=0.75,cex.axis=0.5)
lines(x1,as.numeric(as.character(nim[[7]])),type="l",col="black")
lines(x1,as.numeric(as.character(nim[[8]])),type="l",col="red")
lines(x1,as.numeric(as.character(nim[[9]])),type="l",col="blue")
legend("topright",pch="_",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.75,pt.cex=.5)
with(nim,{for(i in 1:length(nim[[4]]))
        if(nim[[4]][i]=="?")
                nim[[4]][i]<-NA })
plot(x1,as.numeric(as.character(nim[[4]])),type="n",xlab="datetime",ylab="Global_reactive_power",cex.lab=0.75,cex.axis=0.5)
lines(x1,as.numeric(as.character(nim[[4]])),type="l",col="black")
graphics.off()

