url<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url,destfile="./a.zip")
library(data.table)
nim<-read.table(unzip("./a.zip","household_power_consumption.txt"),sep=";",header=TRUE)
nim$Date<-as.Date(nim$Date,"%d/%m/%Y")
nim[[2]]<-as.character(nim[[2]])
nim[[2]]<-as.ITime(nim[[2]],format="%H:%M:%S")
x<-as.Date(c("2007-02-01","2007-02-02"))
nim<-nim[(nim$Date==x[1])|(nim$Date==x[2]),]
x1<-as.POSIXct(paste(nim[[1]],nim[[2]]))
with(nim,{for(i in 1:length(nim[[7]]))
             if(nim[[7]][i]=="?")
                    nim[[7]][i]<-NA })
with(nim,{for(i in 1:length(nim[[8]]))
        if(nim[[8]][i]=="?")
                nim[[8]][i]<-NA })
png(filename="plot3.png",height=480,width=480)
plot(x1,as.numeric(as.character(nim[[7]])),type="n",xlab="",ylab="Energy sub metering",cex.lab=0.75,cex.axis=0.75)
lines(x1,as.numeric(as.character(nim[[7]])),type="l",col="black")
lines(x1,as.numeric(as.character(nim[[8]])),type="l",col="red")
lines(x1,as.numeric(as.character(nim[[9]])),type="l",col="blue")
legend("topright",pch="_",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.75,pt.cex=1.5)
graphics.off()